sylius_twig_hooks:
    hooks:
        'sylius_admin.product_variant.create.content':
            form:
                component: 'sylius_admin:product_variant:form'
                props:
                    resource: '@=_context.resource'
                    product: '@=_context.resource.getProduct()'
                    form: '@=_context.form'
                    template: '@SyliusAdmin/product_variant/form.html.twig'
                configuration:
                    render_rest: false
                priority: 0

        'sylius_admin.product_variant.create.content.header':
            breadcrumbs:
                template: '@SyliusAdmin/product_variant/form/content/create/header/breadcrumbs.html.twig'
                priority: 0

        'sylius_admin.product_variant.create.content.form':
            side_navigation:
                template: '@SyliusAdmin/product_variant/form/side_navigation.html.twig'
                priority: 100
            sections:
                template: '@SyliusAdmin/product_variant/form/sections.html.twig'
                priority: 0

        'sylius_admin.product_variant.create.content.form.side_navigation':
            general:
                template: '@SyliusAdmin/product_variant/form/side_navigation/general.html.twig'
                configuration:
                    active: true
                priority: 400
            channel_pricing:
                template: '@SyliusAdmin/product_variant/form/side_navigation/channel_pricing.html.twig'
                priority: 300
            inventory:
                template: '@SyliusAdmin/product_variant/form/side_navigation/inventory.html.twig'
                priority: 200
            translations:
                template: '@SyliusAdmin/product_variant/form/side_navigation/translations.html.twig'
                priority: 100
            taxes:
                template: '@SyliusAdmin/product_variant/form/side_navigation/taxes.html.twig'
                priority: 0

        'sylius_admin.product_variant.create.content.form.sections':
            general:
                template: '@SyliusAdmin/product_variant/form/sections/general.html.twig'
                priority: 400
            channel_pricing:
                template: '@SyliusAdmin/product_variant/form/sections/channel_pricing.html.twig'
                priority: 300
            inventory:
                template: '@SyliusAdmin/product_variant/form/sections/inventory.html.twig'
                priority: 200
            translations:
                template: '@SyliusAdmin/product_variant/form/sections/translations.html.twig'
                priority: 100
            taxes:
                template: '@SyliusAdmin/product_variant/form/sections/taxes.html.twig'
                priority: 0

        'sylius_admin.product_variant.create.content.form.sections.translations':
            name:
                template: '@SyliusAdmin/product_variant/form/sections/translations/name.html.twig'
                priority: 0
